
- hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: create hcooh user with ssh key
      user: 
        name: hcooh
        uid: 1000
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_file: .ssh/id_ed25519

    - name: Display SSH public key for github
      debug:
        msg: 
          - The value of public ssh key id_ed25519.pub is
          - "{{lookup('file', '/home/hcooh/.ssh/id_ed25519.pub') }}"