
- hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: create ansible user with ssh key
      user: 
        name: ansible
        uid: 900
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_file: .ssh/id_ed25519

    - name: Allow ansible user to run any cmd with sudo
      # https://docs.ansible.com/ansible/latest/collections/community/general/sudoers_module.html
      community.general.sudoers:
        name: ansible
        state: present
        user: ansible
        nopassword: true
        commands: ALL
        runas: ALL

    - name: Display SSH public key for github
      debug:
        msg: 
          - The value of public ssh key id_ed25519.pub is
          - "{{lookup('file', '/home/ansible/.ssh/id_ed25519.pub') }}"